[tool.poetry]
name = "udacity-ai-trading-strategies"
version = "0.1.0"
description = ""
authors = ["Jakub Zapletal <jakub.zapletal@eon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
